wheat=1
beetroots=1.2
carrots=1
potatoes=1
melon=2
pumpkin=2
torchflower_crop=5
pitcher_crop=6
cocoa=1.5
sugar_cane=0.8
cactus=0.8
brown_mushroom=1.5
brown_mushroom_block=3
mushroom_stem=2.5
red_mushroom=1.5
red_mushroom_block=3
kelp=0.5
nether_wart=3