amethyst_block=3
amethyst_cluster=8
ancient_debris=40
andesite=1
basalt=1
bedrock=1000000
blackstone=1
blue_ice=1
budding_amethyst=6 # worth more than amethyst_block
calcite=1
cinnabar=1
clay=1.5
coal_ore=2
copper_ore=2
deepslate=1
deepslate_coal_ore=10
deepslate_copper_ore=3
deepslate_diamond_ore=15
deepslate_emerald_ore=20
deepslate_gold_ore=9
deepslate_iron_ore=7
deepslate_lapis_ore=8
deepslate_redstone_ore=7
diamond_ore=12
diorite=1
dirt=0.3
emerald_ore=17
end_stone=1
glowstone=2
gold_ore=6
granite=1
grass_block=0.4
gravel=0.9
ice=0.1
iron_ore=4
lapis_ore=5
mycelium=0.5
nether_gold_ore=4
nether_quartz_ore=3
netherrack=0.5
packed_ice=0.5
petrified_oak_slab=5
red_sand=0.9
redstone_ore=4
sand=0.9
soul_sand=1
soul_soil=1
stone=1
sulfur=1
tuff=1